# Generated by Django 5.1 on 2024-08-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionModel',
            new_name='PermissionCustomModel',
        ),
    ]
