# Generated by Django 5.1 on 2024-09-01 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0002_rename_permissionmodel_permissioncustommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charr', models.CharField(max_length=50, verbose_name='character field')),
                ('textt', models.TextField(verbose_name='text field')),
                ('booleann', models.BooleanField(verbose_name='boolean field')),
                ('score', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('url', models.URLField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to='Documents/')),
                ('video', models.FileField(upload_to='Videos', verbose_name='video field')),
            ],
        ),
    ]
